AppBundle\Domain\TripMeasures:
    type: entity
    table: trip_measures
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        distance:
            type: float
    manyToOne:
        trips:
            targetEntity: AppBundle\Domain\Trips
            inversedBy: tripMeasures
            joinColumn:
                name: trip_id
                referencedColumnName: id